# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0


# This is a basic workflow to help you get started with Actions

name: Build and Test C++ and Python

# Controls when the workflow will run
on:
  # run pipeline on push event of main or release branch
  push:
    branches:
      - main
      - 'release/**'
  # run pipeline on pull request
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-cpp-test-linux:
    if: (github.event_name == 'push')  || (github.event_name == 'workflow_dispatch') || (!startsWith(github.head_ref, 'release'))
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build-option: [ Debug, Release ]
        cpp-compiler: [g++-11, clang++-14]
    env:
      CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
      CXX: ${{ matrix.cpp-compiler }}

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
      - name: Install C++ dependencies
        run: |
          brew install boost eigen nlohmann-json doctest
      - name: Run build script
        run: ./build.sh  ${{ matrix.build-option }}

  build-cpp-test-windows:
    if: (github.event_name == 'push')  || (github.event_name == 'workflow_dispatch') || (!startsWith(github.head_ref, 'release'))
    runs-on: windows-latest
    strategy:
      matrix:
        build-option: [ Debug, Release ]

    steps:
      - uses: actions/checkout@v3

      - name: Activate conda
        run: |
          & "$env:CONDA\condabin\conda" init

      - name: Install conda environment
        run: |
          conda create --yes -p C:\conda_envs\cpp_pkgs -c conda-forge boost-cpp eigen nlohmann_json doctest

      - name: Build and test
        run: |
          $vsPath = &(Join-Path ${env:ProgramFiles(x86)} '\Microsoft Visual Studio\Installer\vswhere.exe') -property installationpath
          Import-Module (Join-Path $vsPath 'Common7\Tools\Microsoft.VisualStudio.DevShell.dll')
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments '-arch=x64 -host_arch=x64'
          mkdir cpp_build_${{ matrix.build-option }}
          cd cpp_build_${{ matrix.build-option }}
          # generate cmake cache
          cmake .. `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=${{ matrix.build-option }} `
            -DCMAKE_PREFIX_PATH=C:\conda_envs\cpp_pkgs\Library `
            -DPOWER_GRID_MODEL_BUILD_BENCHMARK=1
          # build
          cmake --build . --verbose -j 1
          # test
          .\tests\cpp_unit_tests\power_grid_model_unit_tests.exe

  build-cpp-test-macos:
    if: (github.event_name == 'push')  || (github.event_name == 'workflow_dispatch') || (!startsWith(github.head_ref, 'release'))
    runs-on: macos-latest
    strategy:
      matrix:
        build-option: [ Debug, Release ]
    env:
      CC: clang
      CXX: clang++
      CMAKE_PREFIX_PATH: /usr/local

    steps:
      - uses: actions/checkout@v3

      - name: Install cpp dependencies
        run: |
          brew install ninja boost eigen nlohmann-json doctest

      - name: Build and test
        run: |
          ./build.sh  ${{ matrix.build-option }} 

  build-and-test-python:
    strategy:
      matrix:
        platform: [ linux, macos, windows ]
        include:
          - platform: linux
            os: ubuntu-latest
            cc: gcc
            cxx: g++
            cibw_build: "cp*-manylinux_x86_64 cp*-manylinux_aarch64"
            archs: "x86_64 aarch64"
          - platform: macos
            os: macos-latest
            cc: clang
            cxx: clang++
            cibw_build: cp*-macosx_*
            archs: "x86_64 arm64"
          - platform: windows
            os: windows-latest
            cc:
            cxx:
            cibw_build: cp*-win_amd64
            archs: AMD64

    runs-on: ${{ matrix.os }}
    needs: [build-cpp-test-linux, build-cpp-test-windows, build-cpp-test-macos]

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      CIBW_BUILD_VERBOSITY: 1
      CIBW_BUILD_FRONTEND: "build"
      CIBW_BUILD: ${{ matrix.cibw_build }}
      CIBW_ARCHS: ${{ matrix.archs }}
      CIBW_TEST_EXTRAS: "dev"
      CIBW_TEST_COMMAND: pytest {package}/tests
      # Skip trying to test arm64 builds on Intel Macs
      CIBW_TEST_SKIP: "*-macosx_arm64 *-macosx_universal2:arm64"
      CIBW_ENVIRONMENT_PASS_LINUX: GITHUB_SHA GITHUB_REF GITHUB_RUN_NUMBER CC CXX
      MACOSX_DEPLOYMENT_TARGET: 10.15
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
      CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: matrix.platform == 'linux'
        uses: docker/setup-qemu-action@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1

      - name: Keep wheel files
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl

  publish-wheels:
    needs: build-and-test-python
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USER }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - uses: actions/download-artifact@v3
        with:
          name: wheelhouse
          path: wheelhouse

      - name: List assets
        run: |
          ls ./wheelhouse/*.whl -al

      - name: Get tag
        id: tag
        run: echo "::set-output name=tag::v$(ls ./wheelhouse/*cp310*manylinux2014_x86_64*.whl | awk -F'[-]' '{print $2}')"

      - name: Display tag
        run: echo "${{ steps.tag.outputs.tag }}"

      - name: Upload wheels
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch')
        run: |
          pip install twine
          echo "Publish to PyPI..."
          twine upload --verbose wheelhouse/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch')
        with:
          files: |
            ./wheelhouse/*.whl
          tag_name: ${{ steps.tag.outputs.tag }}
          prerelease: ${{ contains(steps.tag.outputs.tag, 'rc') }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
